export const GET_EMAIL_ANALYTICS = "GET_EMAIL_ANALYTICS";
export const GET_EMAIL_ANALYTICS_SUCCESS = "GET_EMAIL_ANALYTICS_SUCCESS";
export const GET_EMAIL_ANALYTICS_ERROR = "GET_EMAIL_ANALYTICS_ERROR";

export const GET_TEXT_ANALYTICS = "GET_TEXT_ANALYTICS";
export const GET_TEXT_ANALYTICS_SUCCESS = "GET_TEXT_ANALYTICS_SUCCESS";
export const GET_TEXT_ANALYTICS_ERROR = "GET_TEXT_ANALYTICS_ERROR";

export const GET_APPOINTMENT_ANALYTICS = "GET_APPOINTMENT_ANALYTICS";
export const GET_APPOINTMENT_ANALYTICS_SUCCESS =
  "GET_APPOINTMENT_ANALYTICS_SUCCESS";
export const GET_APPOINTMENT_ANALYTICS_ERROR =
  "GET_APPOINTMENT_ANALYTICS_ERROR";

export const GET_OVERALL_ANALYTICS = "GET_OVERALL_ANALYTICS";
export const GET_OVERALL_ANALYTICS_SUCCESS = "GET_OVERALL_ANALYTICS_SUCCESS";
export const GET_OVERALL_ANALYTICS_ERROR = "GET_OVERALL_ANALYTICS_ERROR";
