export const GET_MOVERS = "GET_MOVERS";
export const GET_MOVERS_SUCCESS = "GET_MOVERS_SUCCESS";
export const GET_MOVERS_ERROR = "GET_MOVERS_ERROR";

// export const POST_MOVERS = "POST_MOVERS";
// export const POST_MOVERS_SUCCESS = "POST_MOVERS_SUCCESS";
// export const POST_MOVERS_ERROR = "POST_MOVERS_ERROR";

export const CANCEL_MOVER = "CANCEL_MOVER";
export const CANCEL_MOVER_SUCCESS = "CANCEL_MOVER_SUCCESS";
export const CANCEL_MOVER_ERROR = "CANCEL_MOVER_ERROR";

export const CANCEL_ENTIRE_MOVER_ORDER = "CANCEL_ENTIRE_MOVER_ORDER";
export const CANCEL_ENTIRE_MOVER_ORDER_SUCCESS =
  "CANCEL_ENTIRE_MOVER_ORDER_SUCCESS";
export const CANCEL_ENTIRE_MOVER_ORDER_ERROR =
  "CANCEL_ENTIRE_MOVER_ORDER_ERROR";

  //Get DIY

  export const GET_DIY = "GET_DIY";
export const GET_DIY_SUCCESS = "GET_DIY_SUCCESS";
export const GET_DIY_ERROR = "GET_DIY_ERROR";
