export const GET_OURVENDOR = "GET_OURVENDOR";
export const GET_OURVENDOR_SUCCESS = "GET_OURVENDOR_SUCCESS";
export const GET_OURVENDOR_ERROR = "GET_OURVENDOR_ERROR";

export const POST_ORDER = "POST_ORDER";
export const POST_ORDER_SUCCESS = "POST_ORDER_SUCCESS";
export const POST_ORDER_ERROR = "POST_ORDER_ERROR";

export const CANCEL_HOMEPROS_ORDER = "CANCEL_HOMEPROS_ORDER";
export const CANCEL_HOMEPROS_ORDER_SUCCESS = "CANCEL_HOMEPROS_ORDER_SUCCESS";
export const CANCEL_HOMEPROS_ORDER_ERROR = "CANCEL_HOMEPROS_ORDER_ERROR";
