export const GET_AGGREGATE_SALE = "GET_AGGREGATE_SALE";
export const GET_AGGREGATE_SALE_SUCCESS = "GET_AGGREGATE_SALE_SUCCESS";
export const GET_AGGREGATE_SALE_ERROR = "GET_AGGREGATE_SALE_ERROR";

export const GET_OVERALL_UNIT_SALE = "GET_OVERALL_UNIT_SALE";
export const GET_OVERALL_UNIT_SALE_SUCCESS = "GET_OVERALL_UNIT_SALE_SUCCESS";
export const GET_OVERALL_UNIT_SALE_ERROR = "GET_OVERALL_UNIT_SALE_ERROR";

export const GET_DIGITAL_UNIT_SALE = "GET_DIGITAL_UNIT_SALE";
export const GET_DIGITAL_UNIT_SALE_SUCCESS = "GET_DIGITAL_UNIT_SALE_SUCCESS";
export const GET_DIGITAL_UNIT_SALE_ERROR = "GET_DIGITAL_UNIT_SALE_ERROR";

export const GET_DIGITAL_UNITS_BY_PROVIDERS = "GET_DIGITAL_UNITS_BY_PROVIDERS";
export const GET_DIGITAL_UNITS_BY_PROVIDERS_SUCCESS =
  "GET_DIGITAL_UNITS_BY_PROVIDERS_SUCCESS";
export const GET_DIGITAL_UNITS_BY_PROVIDERS_ERROR =
  "GET_DIGITAL_UNITS_BY_PROVIDERS_ERROR";

export const GET_AGGREGATE_SALE_STATS = "GET_AGGREGATE_SALE_STATS";
export const GET_AGGREGATE_SALE_STATS_SUCCESS =
  "GET_AGGREGATE_SALE_STATS_SUCCESS";
export const GET_AGGREGATE_SALE_STATS_ERROR = "GET_AGGREGATE_SALE_STATS_ERROR";

export const GET_OVERALL_UNIT_SALE_STATS = "GET_OVERALL_UNIT_SALE_STATS";
export const GET_OVERALL_UNIT_SALE_STATS_SUCCESS =
  "GET_OVERALL_UNIT_SALE_STATS_SUCCESS";
export const GET_OVERALL_UNIT_SALE_STATS_ERROR =
  "GET_OVERALL_UNIT_SALE_STATS_ERROR";

export const GET_DIGITAL_UNIT_SALE_STATS = "GET_DIGITAL_UNIT_SALE_STATS";
export const GET_DIGITAL_UNIT_SALE_STATS_SUCCESS =
  "GET_DIGITAL_UNIT_SALE_STATS_SUCCESS";
export const GET_DIGITAL_UNIT_SALE_STATS_ERROR =
  "GET_DIGITAL_UNIT_SALE_STATS_ERROR";

export const GET_DIGITAL_UNITS_BY_PROVIDERS_STATS =
  "GET_DIGITAL_UNITS_BY_PROVIDERS_STATS";
export const GET_DIGITAL_UNITS_BY_PROVIDERS_STATS_SUCCESS =
  "GET_DIGITAL_UNITS_BY_PROVIDERS_STATS_SUCCESS";
export const GET_DIGITAL_UNITS_BY_PROVIDERS_STATS_ERROR =
  "GET_DIGITAL_UNITS_BY_PROVIDERS_STATS_ERROR";
