// get move
export const MOVE_API_GET = "MOVE_API_GET";
export const MOVE_API_GET_SUCCESS = "MOVE_API_GET_SUCCESS";
export const MOVE_API_GET_ERROR = "MOVE_API_GET_ERROR";

// update move
export const MOVE_ADDRESS_UPDATE = "MOVE_ADDRESS_UPDATE";
export const MOVE_ADDRESS_UPDATE_SUCCESS = "MOVE_ADDRESS_UPDATE_SUCCESS";
export const MOVE_ADDRESS_UPDATE_ERROR = "MOVE_ADDRESS_UPDATE_ERROR";

// update move source
export const UPDATE_MOVE_SOURCE_HOME_INFORMATION =
  "UPDATE_MOVE_SOURCE_HOME_INFORMATION";
export const UPDATE_MOVE_SOURCE_HOME_INFORMATION_SUCCESS =
  "UPDATE_MOVE_SOURCE_HOME_INFORMATION_SUCCESS";
export const UPDATE_MOVE_SOURCE_HOME_INFORMATION_ERROR =
  "UPDATE_MOVE_SOURCE_HOME_INFORMATION_ERROR";

// update move destination
export const UPDATE_MOVE_DESTINATION_HOME_INFORMATION =
  "UPDATE_MOVE_DESTINATION_HOME_INFORMATION";
export const UPDATE_MOVE_DESTINATION_HOME_INFORMATION_SUCCESS =
  "UPDATE_MOVE_DESTINATION_HOME_INFORMATION_SUCCESS";
export const UPDATE_MOVE_DESTINATION_HOME_INFORMATION_ERROR =
  "UPDATE_MOVE_DESTINATION_HOME_INFORMATION_ERROR";

//get script data
export const SCRIPT_API_GET = "SCRIPT_API_GET";
export const SCRIPT_API_GET_SUCCESS = "SCRIPT_API_GET_SUCCESS";
export const SCRIPT_API_GET_ERROR = "SCRIPT_API_GET_ERROR";

//get move with hashcode
export const MOVE_API_GET_WITH_HASHCODE = "MOVE_API_GET_WITH_HASHCODE";
export const MOVE_API_GET_WITH_HASHCODE_SUCCESS =
  "MOVE_API_GET_WITH_HASHCODE_SUCCESS";
export const MOVE_API_GET_WITH_HASHCODE_ERROR =
  "MOVE_API_GET_WITH_HASHCODE_ERROR";

export const APPOINTMENTS_POST = "APPOINTMENTS_POST";
export const APPOINTMENTS_POST_SUCCESS = "APPOINTMENTS_POST_SUCCESS";
export const APPOINTMENTS_POST_ERROR = "APPOINTMENTS_POST_ERROR";

//user details
export const USER_API_GET = "USER_API_GET";
export const USER_API_GET_SUCCESS = "USER_API_GET_SUCCESS";
export const USER_API_GET_ERROR = "USER_API_GET_ERROR";

//order details

export const ORDER_API_GET = "ORDER_API_GET";
export const ORDER_API_GET_SUCCESS = "ORDER_API_GET_SUCCESS";
export const ORDER_API_GET_ERROR = "ORDER_API_GET_ERROR";

//brokergae details
export const BROKERAGE_API_GET = "BROKERAGE_API_GET";
export const BROKERAGE_API_GET_SUCCESS = "BROKERAGE_API_GET_SUCCESS";
export const BROKERAGE_API_GET_ERROR = "BROKERAGE_API_GET_ERROR";

//realtor details
export const REALTOR_API_GET = "REALTOR_API_GET";
export const REALTOR_API_GET_SUCCESS = "REALTOR_API_GET_SUCCESS";
export const REALTOR_API_GET_ERROR = "REALTOR_API_GET_ERROR";

//account post

export const ACCOUNT_POST = "ACCOUNT_POST";
export const ACCOUNT_POST_SUCCESS = "ACCOUNT_POST_SUCCESS";
export const ACCOUNT_POST_ERROR = "ACCOUNT_POST_ERROR";

//internet extra post

export const EXTRA_POST = "EXTRA_POST";
export const EXTRA_POST_SUCCESS = "EXTRA_POST_SUCCESS";
export const EXTRA_POST_ERROR = "EXTRA_POST_ERROR";

export const NO_SHOW = "NO_SHOW";
export const NO_SHOW_SUCCESS = "NO_SHOW_SUCCESS";
export const NO_SHOW_ERROR = "NO_SHOW_ERROR";

export const NO_ANSWER = "NO_ANSWER";
export const NO_ANSWER_SUCCESS = "NO_ANSWER_SUCCESS";
export const NO_ANSWER_ERROR = "NO_ANSWER_ERROR";

export const START_WORKFLOW = "START_WORKFLOW";
export const START_WORKFLOW_SUCCESS = "START_WORKFLOW_SUCCESS";
export const START_WORKFLOW_ERROR = "START_WORKFLOW_ERROR";

export const GET_NOTES = "GET_NOTES";
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";
export const GET_NOTES_ERROR = "GET_NOTES_ERROR";

export const ADD_NOTES = "ADD_NOTES";
export const ADD_NOTES_SUCCESS = "ADD_NOTES_SUCCESS";
export const ADD_NOTES_ERROR = "ADD_NOTES_ERROR";

export const UPDATE_NOTES = "UPDATE_NOTES";
export const UPDATE_NOTES_SUCCESS = "UPDATE_NOTES_SUCCESS";
export const UPDATE_NOTES_ERROR = "UPDATE_NOTES_ERROR";

export const UPDATE_PRIMARY_CONTACT = "UPDATE_PRIMARY_CONTACT";
export const UPDATE_PRIMARY_CONTACT_SUCCESS = "UPDATE_PRIMARY_CONTACT_SUCCESS";
export const UPDATE_PRIMARY_CONTACT_ERROR = "UPDATE_PRIMARY_CONTACT_ERROR";

export const UPDATE_ORDER_REMARK = "UPDATE_ORDER_REMARK";
export const UPDATE_ORDER_REMARK_SUCCESS = "UPDATE_ORDER_REMARK_SUCCESS";
export const UPDATE_ORDER_REMARK_ERROR = "UPDATE_ORDER_REMARK_ERROR";

//skip post
export const POST_SKIP_SERVICE = "POST_SKIP_SERVICE";
export const POST_SKIP_SERVICE_SUCCESS = "POST_SKIP_SERVICE_SUCCESS";
export const POST_SKIP_SERVICE_ERROR = "POST_SKIP_SERVICE_ERROR";

export const GET_SKIP_SERVICE = "GET_SKIP_SERVICE";
export const GET_SKIP_SERVICE_SUCCESS = "GET_SKIP_SERVICE_SUCCESS";
export const GET_SKIP_SERVICE_ERROR = "GET_SKIP_SERVICE_ERROR";
